# Generated by Django 4.2.16 on 2024-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0052_auto_20241030_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="bulk_created",
            field=models.BooleanField(
                default=False,
                help_text="Annotation was created in bulk mode",
                verbose_name="bulk created",
            ),
        ),
    ]
