# Generated by Django 5.1.5 on 2025-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ml_model_providers",
            "0006_modelproviderconnection_google_application_credentials_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modelproviderconnection",
            name="provider_choice",
            field=models.CharField(
                blank=True, help_text="Model provider name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelproviderconnection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("OpenAI", "OpenAI"),
                    ("AzureOpenAI", "AzureOpenAI"),
                    ("VertexAI", "VertexAI"),
                    ("Custom", "Custom"),
                ],
                default="OpenAI",
                editable=False,
                help_text="Deprecated in favor of provider_choice",
                max_length=255,
            ),
        ),
    ]
